#!/usr/bin/env bash

TMP_DIR=/tmp/licpro-php-slides

git stash

landslide part1.cfg
landslide part2.cfg

rm -rf $TMP_DIR
mkdir $TMP_DIR
mv index* $TMP_DIR
mv themes/ $TMP_DIR

git checkout gh-pages

mv $TMP_DIR/* .
git add index* themes/avalanche/avalanche/css/font-awesome/
git commit -m "Publish slides (`date`)"

git push origin gh-pages -f

git clean -fdx

git checkout master

git stash apply
