#!/usr/bin/env bash

TMP_DIR=/tmp/licpro-php-slides

git stash

landslide part1.cfg
landslide part2.cfg

rm -rf $TMP_DIR
mkdir $TMP_DIR
mv index* $TMP_DIR
mv css/ $TMP_DIR

git checkout gh-pages

rm -rf css/ index.*

mv $TMP_DIR/index* .
mv $TMP_DIR/css/ .
git add index* css/font-awesome/
git commit --amend -m "Publish slides"

git push origin gh-pages -f

git checkout master
git stash apply
